#!/usr/bin/env python3
"""
bootstrap.py
============
Scaffolding script for the cyberdream project.

Creates the exact directory tree specified for the project and drops a
minimal, docstring-only stub into every Python file that doesn't already
exist. Never overwrites an existing file unless --force is passed.

Usage
-----
    python bootstrap.py            # create missing dirs/files only
    python bootstrap.py --force    # overwrite stub files too
    python bootstrap.py --dry-run  # print what would happen, do nothing
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# --------------------------------------------------------------------------
# Directories to create (order doesn't matter, mkdir -p semantics)
# --------------------------------------------------------------------------
DIRS = [
    "configs",
    "data/raw/CIC-IDS-2018",
    "data/raw/CTU-13",
    "data/processed",
    "data/graphs",
    "src",
    "src/pipeline",
    "src/core",
    "src/heads",
    "src/simulator",
    "src/explainability",
    "src/evaluation",
    "src/utils",
    "app",
    "app/pages",
    "app/utils",
    "experiments",
    "tests",
]

# --------------------------------------------------------------------------
# Files to create, mapped to their initial content.
# Empty string "" -> just touch the file (used for __init__.py / .gitkeep).
# --------------------------------------------------------------------------
INIT_DOCSTRING = '"""{pkg} package."""\n'

FILES: dict[str, str] = {
    # -- package markers --
    "src/__init__.py": INIT_DOCSTRING.format(pkg="cyberdreamer.src"),
    "src/pipeline/__init__.py": INIT_DOCSTRING.format(pkg="pipeline"),
    "src/core/__init__.py": INIT_DOCSTRING.format(pkg="core"),
    "src/heads/__init__.py": INIT_DOCSTRING.format(pkg="heads"),
    "src/simulator/__init__.py": INIT_DOCSTRING.format(pkg="simulator"),
    "src/explainability/__init__.py": INIT_DOCSTRING.format(pkg="explainability"),
    "src/evaluation/__init__.py": INIT_DOCSTRING.format(pkg="evaluation"),
    "src/utils/__init__.py": INIT_DOCSTRING.format(pkg="utils"),
    "app/utils/__init__.py": INIT_DOCSTRING.format(pkg="app.utils"),
    # -- .gitkeep placeholders for otherwise-empty dirs --
    "data/raw/CIC-IDS-2018/.gitkeep": "",
    "data/raw/CTU-13/.gitkeep": "",
    "data/processed/.gitkeep": "",
    "data/graphs/.gitkeep": "",
    "experiments/.gitkeep": "",
}

# Source stub files are written separately (see STUB_SOURCE below) because
# their content is authored per-file rather than templated.


def ensure_dir(path: Path, dry_run: bool) -> None:
    if dry_run:
        print(f"[dry-run] mkdir -p {path}")
        return
    path.mkdir(parents=True, exist_ok=True)


def ensure_file(path: Path, content: str, force: bool, dry_run: bool) -> None:
    rel = path.relative_to(ROOT).as_posix()
    if path.exists() and not force:
        print(f"[skip]     {rel} (already exists, use --force to overwrite)")
        return
    if dry_run:
        action = "overwrite" if path.exists() else "create"
        print(f"[dry-run] {action} {rel}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"[write]    {rel}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold the CyberDreamer project structure.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing stub files.")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen without writing anything.")
    args = parser.parse_args()

    print("== cyberdream bootstrap ==")
    print(f"Root: {ROOT}\n")

    print("-- creating directories --")
    for rel in DIRS:
        ensure_dir(ROOT / rel, args.dry_run)

    print("\n-- writing package / placeholder files --")
    for rel, content in FILES.items():
        ensure_file(ROOT / rel, content, args.force, args.dry_run)

    print(
        "\nNote: the module stub files under src/, app/, and tests/ "
        "(feature_fusion.py, world_model.py, app.py, test_core.py, ...) "
        "ship pre-written in this repository and are not regenerated by "
        "this script. Delete/edit them directly if you need to reset one."
    )

    print("\nDone. Next steps:")
    print("  1. python -m venv .venv && source .venv/bin/activate")
    print("  2. pip install -r requirements.txt")
    print("  3. pip install -e .")
    print("  4. Review configs/default.yaml and adjust paths/hyperparameters")
    print("  5. streamlit run app/app.py")


if __name__ == "__main__":
    main()
